# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

nombre: Crear e implementar una aplicación ASP.Net Core en Azure Web App - turnoslacocaweb

en:
  empujar:
    sucursales:
      - principal

trabajos:
  construir:
    se ejecuta en: windows-latest

    pasos:
      - usos: acciones/checkout@v4

      - nombre: Configurar .NET Core
        usos: acciones/setup-dotnet@v4
        con:
          versión dotnet: '8.x'

      - nombre: Mostrar variables de entorno
        ejecutar: env

      - nombre: Construir con dotnet
        ejecutar: dotnet build --configuration Release

      - nombre: dotnet publish
        ejecutar: dotnet publish -c Release -o ./myapp

      - nombre: Cargar artefacto para el trabajo de implementación
        usos: acciones/upload-artifact@v4
        con:
          nombre: .net-app
          ruta: ./myapp

  desplegar:
    se ejecuta en: windows-latest
    necesita: construir
    ambiente:
      nombre: 'Producción'
      URL: ${{ pasos.implementación-en-aplicación-web.salidas.aplicación-web-url }}
    permisos:
      id-token: write

    pasos:
      - nombre: Descargar artefacto del trabajo de compilación
        usos: acciones/descargar-artefacto@v4
        con:
          nombre: .net-app
      
      - nombre: Iniciar sesión en Azure
        usos: azure/login@v2
        con:
          ID de cliente: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8885AFFE3F5946ACBF0A4EB4913F4E95 }}
          id de inquilino: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A00DFB95D404CF29D86C89C6F5786EF }}
          id de suscripción: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8493A1ACD86B4F27A213B0BF279432C6 }}

      - nombre: Implementar en la aplicación web de Azure
        id: implementar en aplicación web
        usos: azure/webapps-deploy@v3
        con:
          nombre de la aplicación: 'turnoslacocaweb'
          nombre-ranura: 'Producción'
          paquete: './myapp'
          
